import type { PolicyLookupModel } from './fieldSchema';

export const MOCK_TRADITIONAL_POLICY: PolicyLookupModel = {
  policyNumber: 'POL-TRAD-001',
  customerName: 'Ananya Rao',
  productType: 'Century Income',
  productCode: 'CENTURY_INCOME',
  productCategory: 'Traditional',
  uin: '142N066V02',
  annualPremium: 55000,
  policyTerm: 20,
  premiumPayingTerm: 10,
  premiumsPaid: 6,
  sumAssured: 550000,
  fundValue: 0,
  policyStatus: 'In-Force',
  option: 'Deferred',
  channel: 'Online',
  entryAge: 32,
  gender: 'Female',
  dateOfBirth: '1994-05-12',
  premiumFrequency: 'Yearly',
  premiumStatus: 'Paid',
  dateOfCommencement: '2020-05-01',
  riskCommencementDate: '2020-05-01',
  pendingPremiums: 0,
  survivalBenefitPaid: 120000,
  investmentStrategy: '',
};

export const MOCK_ULIP_POLICY: PolicyLookupModel = {
  policyNumber: 'UL-ROYAL-002',
  customerName: 'Rahul Menon',
  productType: 'e-Wealth Royale',
  productCode: 'EWEALTH-ROYALE',
  productCategory: 'ULIP',
  uin: '142L079V03',
  annualPremium: 120000,
  policyTerm: 15,
  premiumPayingTerm: 7,
  premiumsPaid: 4,
  sumAssured: 1200000,
  fundValue: 420000,
  policyStatus: 'In-Force',
  option: 'Platinum Plus',
  channel: 'Direct Marketing',
  entryAge: 31,
  gender: 'Male',
  dateOfBirth: '1993-10-20',
  premiumFrequency: 'Yearly',
  premiumStatus: 'Paid',
  dateOfCommencement: '2021-10-01',
  riskCommencementDate: '2021-10-01',
  pendingPremiums: 0,
  survivalBenefitPaid: 0,
  investmentStrategy: 'Self-Managed Investment Strategy',
};
