// <auto-generated />
using System;
using InsuranceEngine.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceEngine.Api.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    partial class InsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceEngine.Api.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConditionGroupId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ConditionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogicalOperator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("ProductVersionId");

                    b.ToTable("ConditionGroups");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.DeferredIncomeFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PolicyYear")
                        .HasColumnType("int");

                    b.Property<int>("Ppt")
                        .HasColumnType("int");

                    b.Property<int>("Pt")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DeferredIncomeFactors");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ExcelUploadBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<string>("UploadType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExcelUploadBatches");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ExcelUploadRowError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExcelUploadBatchId")
                        .HasColumnType("int");

                    b.Property<string>("RowData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExcelUploadBatchId");

                    b.ToTable("ExcelUploadRowErrors");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.GmbFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntryAgeMax")
                        .HasColumnType("int");

                    b.Property<int>("EntryAgeMin")
                        .HasColumnType("int");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ppt")
                        .HasColumnType("int");

                    b.Property<int>("Pt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GmbFactors");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.GsvFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FactorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PolicyYear")
                        .HasColumnType("int");

                    b.Property<int>("Ppt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GsvFactors");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.Insurer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Insurers");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.LoyaltyFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PolicyYearFrom")
                        .HasColumnType("int");

                    b.Property<int?>("PolicyYearTo")
                        .HasColumnType("int");

                    b.Property<int>("Ppt")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LoyaltyFactors");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsurerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InsurerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ProductFormula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVersionId");

                    b.ToTable("ProductFormulas");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ProductParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVersionId");

                    b.ToTable("ProductParameters");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ProductVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVersions");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.SsvFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Factor1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Factor2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PolicyYear")
                        .HasColumnType("int");

                    b.Property<int>("Ppt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SsvFactors");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.Condition", b =>
                {
                    b.HasOne("InsuranceEngine.Api.Models.ConditionGroup", "ConditionGroup")
                        .WithMany("Conditions")
                        .HasForeignKey("ConditionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConditionGroup");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ConditionGroup", b =>
                {
                    b.HasOne("InsuranceEngine.Api.Models.ConditionGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId");

                    b.HasOne("InsuranceEngine.Api.Models.ProductVersion", "ProductVersion")
                        .WithMany("ConditionGroups")
                        .HasForeignKey("ProductVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("ProductVersion");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ExcelUploadRowError", b =>
                {
                    b.HasOne("InsuranceEngine.Api.Models.ExcelUploadBatch", "ExcelUploadBatch")
                        .WithMany("RowErrors")
                        .HasForeignKey("ExcelUploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExcelUploadBatch");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.Product", b =>
                {
                    b.HasOne("InsuranceEngine.Api.Models.Insurer", "Insurer")
                        .WithMany("Products")
                        .HasForeignKey("InsurerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurer");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ProductFormula", b =>
                {
                    b.HasOne("InsuranceEngine.Api.Models.ProductVersion", "ProductVersion")
                        .WithMany("Formulas")
                        .HasForeignKey("ProductVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVersion");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ProductParameter", b =>
                {
                    b.HasOne("InsuranceEngine.Api.Models.ProductVersion", "ProductVersion")
                        .WithMany("Parameters")
                        .HasForeignKey("ProductVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVersion");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ProductVersion", b =>
                {
                    b.HasOne("InsuranceEngine.Api.Models.Product", "Product")
                        .WithMany("Versions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ConditionGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ExcelUploadBatch", b =>
                {
                    b.Navigation("RowErrors");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.Insurer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.Product", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InsuranceEngine.Api.Models.ProductVersion", b =>
                {
                    b.Navigation("ConditionGroups");

                    b.Navigation("Formulas");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
